name: Checkstyle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and check with Maven
        run: mvn clean checkstyle:check

      - name: Upload Checkstyle report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
