version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test-master:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
      - run:
          name: Build and generate Javadoc
          command: mvn -B javadoc::javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./target/reports/apidocs
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check

workflows:
  version: 2
  build-and-test-master:
    jobs:
      - build-and-test-master:
          filters:
            branches:
              only:
                - master