version: 2.1

orbs:
  codecov: codecov/codecov@5.0.1
  maven: circleci/maven@1.4.1

jobs:
  build-and-test-master:
    executor:
      name: Executor
      docker:
        - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
            - codecov/upload
      - run:
          name: Clean
          command: mvn clean install
            - codecov/upload

workflows:
  version: 2
  build-and-test-master:
    jobs:
      - build-and-test-master:
          filters:
            branches:
              only:
                - master
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
      - build
      - test
