version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test-master:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
      - run:
          name: Run Checkstyle
          command: mvn -f .circleci/checkstyle.yml checkstyle:check

workflows:
  version: 2
  checkstyle:
    jobs:
      - checkstyle
  build-and-test-master:
    jobs:
      - build-and-test-master:
          filters:
            branches:
              only:
                - master