version: 2.1

jobs:
  build-and-test-master:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  version: 2
  build-and-test-master:
    jobs:
      - build-and-test-master:
          filters:
            branches:
              only:
                - master

orbs:
  codecov: codecov/codecov@5.0.1
  workflows:
    upload-to-codecov:
      jobs:
        - checkout
        - codecov/upload
