name: Java Documentation Generation

on:
  push:
    branches: [master]

jobs:
  generate-docs:
    name: Generate Java Documentation and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generate JavaDocs
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./target/reports/apidocs